### ISSUE TITLE
Не работает выборка с инфоблока, если инфоблок имеет кастомное свойство

### ISSUE THREAD

**Issue by toxaw** [medveddev/bxorm#13]
при exec() на выборку из инфоблока вылетает исключение на таблицу с со свойствами, то что кастомное свойство не является VALUE или нет имеет значение, даже в том случае, если это свойство не участвует запросе.

**Comment by medveddev** [comment]
нужно больше информации, желательно c примером кода.
какой версии инфоблок, что за свойство выбирается, какой sql запрос получается, конкретный текст ошибки или исключения, трейс.

**Comment by toxaw** [comment]
@medveddev 

Закрываю issue, т.к. в последствии была выяснена причина данного поведения.
Причина являлась в том, что через миграции заводились свойства без PROPERTY_TYPE, в следствии чего, в таблицы свойств b_iblock_property было null`ванное значение PROPERTY_TYPE.  Из-за этого ORM для инфоблоков не могла произвести/составить SQL запрос. 


Но это выяснилось уже при исследовании кода самой ORM. 

Было бы неплохо выбрасывать конкретный Exception из плана InvalidPrpertyTypeException "Invalid property type #и ID свойства#" чтобы не проводить повторное исследование, если проблема не знакома.
