### ISSUE TITLE
Разное поведение в посути одинаковой ситуации (ошибка при сохранении)

### ISSUE THREAD

**Issue by Voral** [medveddev/bxorm#14]
Создаем новый элемент. И выполняем save. И две ситуации:
1. Не задали IBLOCK_ID.  ошибку надо ловить в возвращаемом AddResult
2. Добавляем значение не существующего поля 
`$element->sysSetValue('BLA_BLA', 'asdasdas');` - кидает Exception...

Может хорошо будет если  будут ексцепшены кидаться всегда?

**Comment by medveddev** [comment]
такая политика обработки ошибок. в случае валидации данных проблема может быть в том числе в пользовательском вводе, и это не повод прерывать весь процесс
