### ISSUE TITLE
ORM генерирует невалидный запрос, в случае изменения только UF-полей в сущности

### ISSUE THREAD

**Issue by rpecb** [medveddev/bxorm#17]
При изменении в сущности `UF`-поля (при этом оригинальные поля таблицы не менялись и соответственно в статусе `CURRENT` только `UF`-поля), ORM генерирует пустой запрос на обновление полей сущности, например: `UPDATE b_catalog_store SET  WHERE ID IN (123)`, `SET` - пустое.

Если изменить принудительно какое-то поле самой таблицы то все ок отрабатывает.

Примерный контекст:
```php
$collection = StoreTable::query()->...->fetchCollection();

foreach ($collection as $store)
{
    $store->setTitle($newTitle); // тут $newTitle идентичен актуальному значению из БД
    $store->set('UF_MALL', $newMall); // тут $newMall имеет отличное значение от актуального
}

$collection->save(); // `UPDATE b_catalog_store SET  WHERE ID IN (123)`
```

**Comment by medveddev** [comment]
исправлено в main 21.400.0 (750c48fc346f)
