### ISSUE TITLE
[ORM] Некорректное составление запроса на одной из новых версий iblock (s* таблицы)

### ISSUE THREAD

**Issue by staromand** [medveddev/bxorm#18]
На самой актуальной версии iblock (20.0.600) сейчас построение запроса со свойствами стало для b_iblock_element_prop_s* таблиц в селект пихать колонку VALUE.
Это некорректно, ибо в таких таблицах нет вообще этой колонки.

На версии по крайней мере 19.0.50 такого не происходит.

**Comment by medveddev** [comment]
на актуальной версии не воспроизводится. хотелось бы видеть код запроса и результирующий sql.

**Comment by medveddev** [comment]
проверьте на iblock 21.400.0, если проблема остается - обратитесь пожалуйста в техподдержку (вероятно потребуется доступ к установке).
