### ISSUE TITLE
Наследование от \Bitrix\Iblock\Elements\EO_Element32

### ISSUE THREAD

**Issue by north-leshiy** [medveddev/bxorm#2]
Наследование необходимо для 
- возможности расширения и кастомизации логики
- возможности вынесения в модель логики, которая присуща именно данной модели.
- инициализация объектов в дальнейшем из IoC контейнера

**Comment by north-leshiy** [comment]
Сейчас видим что можно только Декоратор сделать с примесью магии чтобы расширить.

**Comment by medveddev** [comment]
реализовано в main 21.500.0, iblock 21.500.0
