### ISSUE TITLE
Баг с выборкой множественного uf поля из hlblock`a.

### ISSUE THREAD

**Issue by toxaw** [medveddev/bxorm#20]
При выборке множественного поля и получение результата в виде объектов получает string свойство со значением `Array` ![image](https://user-images.githubusercontent.com/33651909/86171241-1a70b700-bb25-11ea-9df0-f7505c53598d.png)
При выборке множественного поля и получение результата в виде массива, получаем корректный результат.
![image](https://user-images.githubusercontent.com/33651909/86171659-c4504380-bb25-11ea-8003-7604ca15c32e.png)

**Comment by medveddev** [comment]
в настоящий момент на актуальной версии не воспроизводится. из последнего в main 21.400.0 были связанные с этим правки, дождитесь пожалуйста этого обновления и проверьте, если проблема останется - обратитесь в техподдержку (скорее всего потребуется доступ к установке).
