### ISSUE TITLE
Ошибка при использовании fill() в инфоблоках 2.0

### ISSUE THREAD

**Issue by ghost** [medveddev/bxorm#22]
При попытке заполнить все поля сразу (`fill()`) у инфоблока 2.0 выбрасывается исключение об отсутствии в таблице `iblock_element_prop_s2.VALUE`, хотя там его и не должно быть (там поля `IBLOCK_ELEMENT_ID,` `PROPERTY_*`, `DESCRIPTION_*`).

![изображение](https://user-images.githubusercontent.com/68371448/89017644-4ef1b180-d323-11ea-9135-530725954fa2.png)

![изображение](https://user-images.githubusercontent.com/68371448/89017743-7b0d3280-d323-11ea-8e01-369802a501fc.png)

**Comment by staromand** [comment]
https://github.com/medveddev/bxorm/issues/18

**Comment by medveddev** [comment]
на актуальной версии не воспроизводится. проверьте на iblock 21.400.0, если проблема остается - обратитесь пожалуйста в техподдержку (вероятно потребуется доступ к установке).
