### ISSUE TITLE
Баг при выборке секций элемента с помощью N:M поля SECTIONS сущности элемента ИБ

### ISSUE THREAD

**Issue by rpecb** [medveddev/bxorm#23]
При выборке секций с помощью `ElementTable::query()->...addSelect('SECTIONS.ID')` либо `$collection->fill('SECTIONS.ID')` возникает исключение:

> Unknown field definition `\Bitrix\Iblock\SectionElement:REGULAR_ELEMENT` (\Bitrix\Iblock\SectionElement:REGULAR_ELEMENT.IBLOCK_ELEMENT_ID) for \Bitrix\Iblock\Element Entity.‌‌

Ниже привел конкретное место с комментариями где, судя по всему, баг:

```php
// bitrix/modules/main/lib/orm/query/chain.php:302

/** @var Reference $reference */
$reference = Entity::getInstance($ref_entity_name)->getField($ref_field_name);

if (
    $reference->getRefEntity()->getFullName() == $prev_entity->getFullName() ||
    is_subclass_of( // тут судя по всему неверный порядок аргументов, тк дочерний класс должен идти первым
	$prev_entity->getDataClass(), // ‌\Bitrix\Iblock\ElementTable
        $reference->getRefEntity()->getDataClass() // ‌\Bitrix\Iblock\ORM\CommonElementTable
    )
)
```

**Comment by medveddev** [comment]
в ElementTable нет поля SECTIONS, поэтому ожидаемо вы получаете ошибку.
такое поле есть только сущностях конкретных инфоблоков, но не в общей сущности ElementTable.
