### ISSUE TITLE
не реализованы поля DATE_ACTIVE_FROM, DATE_ACTIVE_TO

### ISSUE THREAD

**Issue by xukku** [medveddev/bxorm#25]
[Bitrix\Main\SystemException] 
Unknown field definition `DATE_ACTIVE_FROM` (DATE_ACTIVE_FROM) for \Bitrix\Iblock\Elements\ElementS1offers Entity. (100)

https://dev.1c-bitrix.ru/api_help/iblock/classes/ciblockelement/getlist.php

**Comment by medveddev** [comment]
поля называются ACTIVE_FROM и ACTIVE_TO
