### ISSUE TITLE
Ошибка в получении значения свойства типа Число используя  ORM

### ISSUE THREAD

**Issue by shopkod** [medveddev/bxorm#26]
Есть свойство елемента инфоблока тип Число.
Пытаюсь получить его значение используя  ORM
`$element = \Bitrix\Iblock\Elements\ElementMyTableApiCodeTable::getList([
   'select' => ['QUANTITY'], // property type "N"
   'limit' =>  1,
])->fetch();
$element->getQuantity()->getValue(); // if value = 0.5 return 0`
Если в значении дробное число, возвращает целую часть, потому что сущность реализована классом Bitrix\Main\ORM\Fields\IntegerField, а не Bitrix\Main\ORM\Fields\FloatField

**Comment by medveddev** [comment]
исправлено в iblock 21.400.0
