### ISSUE TITLE
Не устанавливается множественное числовое свойство в инфоблоках 2.0

### ISSUE THREAD

**Issue by toxaw** [medveddev/bxorm#27]
При сохранении элемента в версии инфоблока 2.0 не проставляется значения у множественное числовых свойств типа `N`. (этот баг только при создании элемента и только в версии 2.0.)
Вот свойства инфоблока:
![image](https://user-images.githubusercontent.com/33651909/121709185-f3ff1e00-cae0-11eb-889b-c6f05f76c5e0.png)

Вот запрос:
![image](https://user-images.githubusercontent.com/33651909/121709250-07aa8480-cae1-11eb-9135-82e15ca0f17d.png)
не 2.0 
![image](https://user-images.githubusercontent.com/33651909/121709517-50fad400-cae1-11eb-9a8b-1f662e36d182.png)
2.0:
![image](https://user-images.githubusercontent.com/33651909/121709429-37f22300-cae1-11eb-8c16-4530d6015c52.png) - Ошибка - не заполнено ПОЛЕ INTEGER_MULTI_FIELD.

Отсылка к issue https://github.com/medveddev/bxorm/issues/8

Версии:

iblock 21.300.0
main 21.300.0

**Comment by medveddev** [comment]
исправлено в iblock 21.400.0 (тикет 138566, ревизия 0ead7b65aa62)
