### ISSUE TITLE
Выборка секций инфоблока через \Bitrix\Iblock\Model\Section

### ISSUE THREAD

**Issue by toxaw** [medveddev/bxorm#34]
При запросе всех секций
![image](https://user-images.githubusercontent.com/33651909/121715109-3297d700-cae7-11eb-9598-6c287d206a66.png)
Мы получаем секции по скомпилированному инфоблоку:
![image](https://user-images.githubusercontent.com/33651909/121715172-3d526c00-cae7-11eb-85f1-e78902d1e3e8.png)
![image](https://user-images.githubusercontent.com/33651909/121715196-42afb680-cae7-11eb-8cb8-a37121347a9b.png)

**И секции по чужим инфоблокам:**
![image](https://user-images.githubusercontent.com/33651909/121715254-51966900-cae7-11eb-8bf9-9f84bdfd5d34.png)
![image](https://user-images.githubusercontent.com/33651909/121715267-55c28680-cae7-11eb-9511-5e6d7a57b644.png)
![image](https://user-images.githubusercontent.com/33651909/121715366-77237280-cae7-11eb-8702-e81e8d618e60.png)

Т.е. получать по скомпилированному инфоблоку все секции.
Конечно, можно передать в выборку where IBLOCK_ID, но это как то странно, если мы скомпилировали для определенного инфоблока, а по факту работаем со всеми.

Второй вопрос, можно ли компилировать сущность не по ID инфоблока а по его API_CODE?

![image](https://user-images.githubusercontent.com/33651909/121715435-8e626000-cae7-11eb-8e23-adbbb3625e75.png)

т.к. данного метода как для IblockTable я не нашел.

Версии:

iblock 21.300.0
main 21.300.0

**Comment by medveddev** [comment]
реализовано в iblock 21.500.0
