### ISSUE TITLE
Наследование от динамически скомпилированной сущности

### ISSUE THREAD

**Issue by toxaw** [medveddev/bxorm#35]
Продолжение обсуждения из issue https://github.com/medveddev/bxorm/issues/2

Наследоваться по от динамически скомпилированной до сих пор невозможно. DataManager не находит свои все свойства после наследования.
Пытаемся наследоваться:
![image](https://user-images.githubusercontent.com/33651909/121715942-1ea0a500-cae8-11eb-99f7-365ca38a2b78.png)
Сделать запрос:
![image](https://user-images.githubusercontent.com/33651909/121715960-23655900-cae8-11eb-97cd-c32267e2a598.png)

И в итоге:
![image](https://user-images.githubusercontent.com/33651909/121716028-3b3cdd00-cae8-11eb-8fe1-68269fba024b.png)

такое не работает.

Но, остается прежний способ расширения для динамических сущностей, через getEntity->addField()
![image](https://user-images.githubusercontent.com/33651909/121716085-4b54bc80-cae8-11eb-9ae4-77bb3ba7932c.png)

Мы уже придумали обертку для  getEntity->addField() чтобы заворачивать расширенные сущности в классы.
![image](https://user-images.githubusercontent.com/33651909/121716304-8951e080-cae8-11eb-990f-46172efa2e2a.png)
И потом работать с ними вот так:
![image](https://user-images.githubusercontent.com/33651909/121716450-b7372500-cae8-11eb-9f9e-5e3f322d3b01.png)

Но это все равно остается неудобным вариантом для расширения сущностей. Более классический, кажется был бы вариант как раз таки через наследование, который на данным момент не работает.

Будет это в последующих версиях orm для инфоблоках ожидаться?

Версии:

iblock 21.300.0
main 21.300.0

**Comment by medveddev** [comment]
реализовано в main 21.500.0, iblock 21.500.0
