### ISSUE TITLE
При попытке включить в выборку множественный файл с ссылкой FILE - получаем ошибку

### ISSUE THREAD

**Issue by north-leshiy** [medveddev/bxorm#5]
![image](https://user-images.githubusercontent.com/5521833/70379797-6e763d00-1942-11ea-9101-275edf49f0f4.png)

**Comment by medveddev** [comment]
если добавить DOCUMENTS в select, то запрос сработает. подумаю, получится ли автоматикой предусмотреть такие случаи

**Comment by north-leshiy** [comment]
Аналогичная проблема с другими связанными полями. 

Плюс на каждый вложенный нужно выбирать primary, было бы удобнее если бы он выбирался автоматом мб?
